version: "2"

services:
    postgres:
        image: postgres:latest
        container_name: postgres
        healthcheck:
          test: ["CMD-SHELL", "pg_isready -U postgres"]
          interval: 5s
          timeout: 5s
          retries: 5
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: root
            POSTGRES_DB: aftas
            PGDATA: /data/postgres
        volumes:
            - postgres:/var/lib/postgresql/data
        ports:
            - "5432:5432"
    frontend:
        image: aftas_fe
        container_name: aftas_fe
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "4200:4200"
        depends_on:
            - backend
    backend:
        image: aftas_be
        build:
            context: .
            dockerfile: Dockerfile
        container_name: aftas_be
        depends_on:
            postgres:
                condition: service_healthy
        environment:
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/aftas
            - SPRING_DATASOURCE_USERNAME=postgres
            - SPRING_DATASOURCE_PASSWORD=root
            - SPRING_JPA_HIBERNATE_DDL_AUTO=update
        ports:
            - "8081:8081"
volumes:
    postgres:
        driver: local
